### ISSUE TITLE
Sort Enum Properties

### ISSUE THREAD

**Issue by seanblonien** [mskelton/eslint-plugin-sort#26]
I love this eslint plugin and how it sorts so much more than other eslint rules/plugins that I've tried.

I am using it to sort type interface properties, but it currently doesn't work on sorting enums within TypeScript. Is this something that exists or something that could be added easily?

Example enum code: 

```ts
export enum MyEnum {
  z,
  b,
  a,
}
```

with rule that would auto-fix/give warning/error about the properties not being sorted, and turn into:

```ts
export enum MyEnum {
  a,
  b,
  z,
}
```

**Comment by mskelton** [comment]
So, enum sorting is tricky as it changes runtime behavior.  Given your first example, the value of each key is:

```ts
export enum MyEnum {
  z, // 0
  b, // 1
  a, // 2
}
```

If you sort it, that changes:

```ts
export enum MyEnum {
  a, // 0
  b, // 1
  z, // 2
}
```

As you can see, the runtime value of each enum property changes.  [This other ESLint plugin](https://github.com/infctr/eslint-plugin-typescript-sort-keys/blob/master/docs/rules/string-enum.md) has a rule for sorting string enums which are safe since the value of each property is explicit.

I never implemented this due to fact that I personally don't use enums so it wasn't something I really cared to implement.  If you are interested in implementing sorting for string enums, I'd happily merge it, but I likely won't add it myself.

**Comment by seanblonien** [comment]
Ah yes, I forgot it would change the enum values unless they were named, you're right. 

Yea that other ESLint plugin pretty much solves my use case for it, so I think I'll just use that plugin. I also don't have too much interest in implementing it myself.
